<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.gwtproject</groupId>
        <artifactId>gwt-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>gwt-servlet</artifactId>
    <name>GWT RPC/RF javax.servlet implementation</name>
    <description>
        GWT-RPC and RequestFactory implementations for use in javax.servlet environments
    </description>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>ext</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <!-- Arguably this shouldn't be included -->
            <groupId>${project.groupId}</groupId>
            <artifactId>javaemul</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>gwt-core</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>gwt-user</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>requestfactory</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <!-- needed by RequestFactory -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <!-- Used for source-mapping in stacktrace deobfuscation for logging -->
            <optional>true</optional>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>${project.groupId}:ext</include>
                                    <include>${project.groupId}:gwt-user</include>
                                    <include>${project.groupId}:javaemul</include>
                                    <include>${project.groupId}:gwt-core</include>
                                    <include>${project.groupId}:requestfactory</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>${project.groupId}:gwt-user</artifact>
                                    <excludes>
                                        <exclude>**/rebind/**</exclude>
                                        <exclude>**/tools/**</exclude>
                                        <exclude>**/super/**</exclude>
                                        <exclude>com/google/gwt/json/**</exclude>
                                        <exclude>com/google/gwt/junit/*</exclude>
                                        <exclude>com/google/gwt/junit/client/GWTTestCase*</exclude>
                                        <exclude>com/google/gwt/junit/server/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>${project.groupId}:core</artifact>
                                    <includes>
                                        <include>com/google/gwt/core/shared/**</include>
                                    </includes>
                                </filter>
                                <filter>
                                    <artifact>${project.groupId}:ext</artifact>
                                    <includes>
                                        <include>com/google/gwt/dev/util/Name*</include>
                                        <include>com/google/gwt/dev/util/StringKey*</include>
                                        <include>com/google/gwt/util/tools/shared/**</include>
                                    </includes>
                                </filter>
                            </filters>
<!--                            <createSourcesJar>true</createSourcesJar>-->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
